import { PageContainer } from "@/components/layout/page-container";
import { PageHeader } from "@/components/layout/page-header";
import { Breadcrumbs } from "@/components/navigation/breadcrumbs";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Notice } from "@/components/ui/notice";
import { StatusLabel } from "@/components/ui/status-label";
import { SectionHeading } from "@/components/ui/typography";

const briefingSections = [
  {
    description: "Recently observed civic records, ready to inspect or save to a notebook.",
    items: ["Regular meeting agenda — July 28", "2027 budget working summary"],
    title: "New documents",
  },
  {
    description: "Meetings in the near term, ordered by scheduled start time.",
    items: ["County Council regular meeting · Jul 28", "Board of Commissioners · Jul 29"],
    title: "Important meetings",
  },
  {
    description: "Recently updated ordinances and budget records, with status preserved from the source record.",
    items: ["No mock policy changes", "No mock budget changes"],
    title: "Policy and budget changes",
  },
  {
    description: "Topics with the most new source assignments, followed by later scheduled events.",
    items: ["Transportation · 4 new records", "Housing · 2 new records"],
    title: "Trending topics",
  },
];

export default function BriefingPage() {
  return (
    <PageContainer className="py-12 sm:py-16">
      <Breadcrumbs items={[{ href: "/dashboard", label: "Dashboard" }, { label: "Daily briefing" }]} />
      <PageHeader
        action={<Button>Subscribe in app</Button>}
        className="mt-8"
        description="A concise, source-linked record of what changed and what is coming next."
        eyebrow="Daily civic briefing"
        title="Friday, July 24"
      />

      <Notice className="mt-8" title="Mock briefing">
        This page demonstrates the in-app briefing experience with mock records. Production briefings are generated by the autonomous worker only for subscribed organizations.
      </Notice>

      <div className="mt-10 grid gap-10 lg:grid-cols-[minmax(0,1fr)_17rem]">
        <main>
          <div className="grid gap-px border border-rule bg-rule sm:grid-cols-2">
            {briefingSections.map((section) => (
              <Card className="p-6" key={section.title}>
                <SectionHeading className="border-0 pb-0">{section.title}</SectionHeading>
                <p className="mt-3 text-sm leading-6 text-ink-muted">{section.description}</p>
                <ul className="mt-5 divide-y divide-rule border-y border-rule text-sm">
                  {section.items.map((item) => (
                    <li className="py-3 text-ink" key={item}>{item}</li>
                  ))}
                </ul>
              </Card>
            ))}
          </div>

          <section className="mt-14" aria-labelledby="upcoming-events-heading">
            <SectionHeading id="upcoming-events-heading">Upcoming events</SectionHeading>
            <div className="mt-5 divide-y divide-rule border-y border-rule">
              <article className="flex flex-wrap items-baseline justify-between gap-4 py-5">
                <div>
                  <div className="flex items-center gap-2"><StatusLabel>Meeting</StatusLabel><span className="text-sm text-ink-muted">County Council</span></div>
                  <h2 className="mt-2 font-serif text-2xl tracking-[-0.02em]">Regular meeting</h2>
                </div>
                <time className="text-sm text-ink-muted">Jul 28 · 6:00 PM</time>
              </article>
            </div>
          </section>
        </main>

        <aside className="border-t border-rule pt-6 lg:border-t-0 lg:border-l lg:pl-7 lg:pt-0">
          <SectionHeading>Briefing notes</SectionHeading>
          <div className="mt-5 space-y-6 text-sm leading-6 text-ink-muted">
            <p>Each item is a direct record link or an aggregate of normalized civic data. The briefing does not infer policy outcomes.</p>
            <p>Subscribing makes a new briefing available in this workspace each day. Email delivery is not enabled in the mock shell.</p>
          </div>
        </aside>
      </div>
    </PageContainer>
  );
}
